### ISSUE TITLE
Use arrow function for all event hanlders

### ISSUE THREAD

**Issue by woanversace** [bumanerdene/pomodoro-react#1]
https://github.com/bumanerdene/pomodoro-react/blob/bbe4c26280fc99328f8661a353819eb175d0cbd8/src/App.js#L19

You can use arrow function to save a lot time to bind

**Comment by bumanerdene** [comment]
Thank u for your feedback~ I tried to fix this issue, If u think its wrong then please spend me little more time to give your feedback again :)
