### ISSUE TITLE
File naming discrepancy

### ISSUE THREAD

**Issue by larilampen** [bumanerdene/pomodoro-react#4]
One of the source files is named `addTask.js`. In the main app file you have this line:

```javascript
import {AddTask} from './AddTask.js';
```

This works on Windows and (the default config of) OS X, but in case-sensitive filesystems like on Linux, the file is not found due to the discrepancy in naming (capital A vs. lower case a).

To fix the issue, you could either change the line, or rename the file. Based on [AirBNB's React style guide](https://github.com/airbnb/javascript/tree/master/react), filenames should use PascalCase and hence the preferred remedy is to rename the file `addTask.js` to `AddTask.js`.

**Comment by bumanerdene** [comment]
Thank u for your feedback :)
